services:
  database:
    image: postgres:16.3-alpine3.20
    container_name: database
    restart: always
    shm_size: 512mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
  test_database:
    image: postgres:16.3-alpine3.20
    container_name: test_database
    restart: always
    shm_size: 512mb
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_TEST: test
    expose:
      - 5433
    ports:
      - "5433:5432"
