services:
  database:
    image: postgres:16.3-alpine3.20
    container_name: database
    restart: always
    shm_size: 1gb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: app
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@database:5432/postgres?schema=public
    volumes:
      - .:/app
    expose:
      - 3000
    ports:
      - "3000:3000"
    command: >
      sh -c "sleep 5 && pnpm install && pnpm exec prisma generate && pnpm exec prisma migrate dev --name init && pnpm dev"
