services:
  database:
    image: postgres:16.3-alpine3.20
    container_name: database
    restart: always
    shm_size: 512mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
  test_database:
    image: postgres:16.3-alpine3.20
    container_name: test_database
    restart: always
    shm_size: 512mb
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    expose:
      - 5433
    ports:
      - "5433:5432"
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@database:5432/postgres?schema=public"
      TEST_DATABASE_URL: "postgresql://test:test@test_database:5432/test?schema=public"
    expose:
      - 3000
    ports:
      - "3000:3000"
    depends_on:
      - database
      - test_database
    volumes:
      - .:/app
