services:
  db:
    image: postgres:16.3-alpine3.20
    container_name: database
    restart: always
    shm_size: 128mb
    hostname: localhost
    env_file:
      -   .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      -   5432
    ports:
      -   5432:5432
  app:
    container_name: myApp
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      -   .env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/postgres?schema=public"
    expose:
      -   3000
    ports:
      -   3000:3000
    volumes:
      -   .:/app
      -   /app/node_modules
    depends_on:
      -   db