import { Inter } from "next/font/google";
import SessionProvider from "@/app/SessionWrapper";
import { getServerSession } from "next-auth";
import Header from "@/components/organism/Header";

import { Provider } from "@/context/store";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <SessionProvider session={session}>
            <Header />
            <main>{children}</main>
          </SessionProvider>
        </Provider>
      </body>
    </html>
  );
}
