name: "Enforce Allowed PR Branches"

#Trigger this workflow on every PR event
on:
  pull_request:
    branches:
      - main
      - develop
      - release

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from an allowed branch
        run: echo "Hello, world"