name: "Enforce Branch Naming Convention"

on:
  push:
    branches:
      - '*'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch name
        run: |
          BRANCH_NAME=$(echo "$(GITHUB_REF#refs/head/}")
          if [[!BRANCH_NAME =~ ^(main|develop|release|hotfix/.+|feat/.+|bug/.+|docs/.+)$]]; then
            echo "Invalid branch name: $BRANCH_NAME"
            exit 1
          fi