name: "Enforce Allowed Branches for PR to release"

on:
  pull_request:
    branches:
      - release

jobs:
  check-pr-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from allowed branch
        run: |
          BASE_BRANCH=$(echo "${{github.base_ref}}")
          SOURCE_BRANCH=$(echo"${{github.head_ref}}")

#          only allow PRs from develop or hotfix/* branches
          if [[$BASE_BRANCH=="release" && ! $$SOURCE_BRANCH =~ ^(docs/.+|bug/.+)$]]; then
            echo "Pull requests to main are only allowed from docs or bug/* branches."
            exit 1
          fi