name: "Enforce Allowed Branches for PR to develop"

on:
  pull_request:
    branches:
      - develop

jobs:
  check-pr-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from allowed branch
        run: |
          BASE_BRANCH=$(echo "${{github.base_ref}}")
          SOURCE_BRANCH=$(echo"${{github.head_ref}}")
          
#           Only allow PRs to develop from feat/* branches
          if [[ $BASE_BRANCH == "develop" && ! $SOURCE_BRANCH =~ ^(feat/.+|release)$ ]]; then
            echo "Pull requests to develop are only allowed from feat/* or release branches."
            exit 1  # Fail the workflow
          fi