name: Enforce PR Reviews

on:
  pull_request:
    branches:
      - main
      - develop
      - release

jobs:
  require-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure PR has enough reviews
        run: |
          reviews=$(gh pr view ${{ github.event.pull_request.number }} --json reviews --jq '.reviews | length')
          if [[ "$reviews" -lt 1 ]]; then
            echo "Error: This PR requires at least 1 approval."
            exit 1
          fi
