name: "Enforce Allowed Branches for PR to Main"

on:
  pull_request:
    branches:
      - main

jobs:
  check-pr-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from allowed branch
        run: |
          BASE_BRANCH=$(echo "${{github.base_ref}}")
          SOURCE_BRANCH=$(echo"${{github.head_ref}}")

#          only allow PRs from develop or hotfix/* branches
          if [[$BASE_BRANCH=="main" && ! $$SOURCE_BRANCH =~ ^(develop|hotfix/.+)$]]; then
            echo "Pull requests to main are only allowed from develop or hotfix/* branches."
            exit 1
          fi
